name: 'deploy-redirect'
on:
  push:
    branches:
      - main

jobs:
  pull:
    uses: appleboy/ssh-action@v1.0.0
    with:
      host: ${{ secrets.deploy-host }}
      username: ${{ secrets.deploy-host-user }}
      key: ${{ secrets.deploy-host-user-key }}
      port: ${{ secrets.deploy-port }}
      script: |
        cd ~/redirect
        git pull
        python ./make-caddy.py
        ./make-caddy.sh
        caddy fmt --overwrite
        mv ./Caddyfile /etc/caddy/Caddyfile
        sudo service caddy reload
