name: 'deploy-redirect'
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_HOST_USER }}
          key: ${{ secrets.DEPLOY_HOST_USER_KEY }}
          port: ${{ secrets.DEPLOY_PORT }}
          script: |
            cd ~/redirect
            echo "Start Date:             $(date -u)" > deploy.log
            git pull
            python ./make-caddy.py
            caddy fmt --overwrite
            mv ./Caddyfile /etc/caddy/Caddyfile
            sudo service caddy reload
            echo "Revision (full):  $(git rev-parse HEAD)" >> deploy.log
            echo "Revision (short): $(git rev-parse --short HEAD)" >> deploy.log
            echo "End Date:             $(date -u)" >> deploy.log