name: 'deploy-redirect'
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.deploy-host }}
          username: ${{ secrets.deploy-host-user }}
          key: ${{ secrets.deploy-host-user-key }}
          port: ${{ secrets.deploy-port }}
          script: |
            cd ~/redirect
            git pull
            python ./make-caddy.py
            caddy fmt --overwrite
            mv ./Caddyfile /etc/caddy/Caddyfile
            sudo service caddy reload
